name: pyjanitor-dev
channels:
- conda-forge
- rdkit
dependencies:
- python>=3.6
- biopython
- black
- bumpversion
- cairo
- conda
- doc8
- flake8
- hypothesis>=4.4.0
- ipykernel
- ipython
- isort
- jupyterlab
- lxml
- make
- missingno
- mypy
- natsort
- nbsphinx
- nox
- numpy>=1.16
- pandas-flavor
- pandas>=1.0.0
- pip
- pipreqs
- pre-commit
- pyflakes
- pylint
- pyspark
- pytest
- pytest-azurepipelines
- pytest-cov
- python-language-server
- rdkit
- recommonmark
- scikit-learn
- seaborn
- sphinx
- sphinxcontrib-fulltoc
- twine
- unyt
- xlrd
- xorg-libxrender
- xarray
- pandas-vet
